---
title: "Untitled"
author: "Maxwel Coura Oliveira"
date: "3/24/2020"
output: html_document
---


```{r}
library(tidyverse)
require(ggimage) 
library(grid)
library(drc)
library(png)
```




```{r}
library(RCurl)
library(glmmTMB)
library(lme4)
library(lmerTest)
library(emmeans)


df_path <- getURL("https://raw.githubusercontent.com/openweedsci/data/master/posts/control.csv")

weedcont <- read_csv(df_path)


model <- glmmTMB(control ~ herbicide + (1|rep), beta_family(link = "logit"), data=weedcont)

lsmeans <- emmeans(model, ~ herbicide, cont="pairwise", adjust="none", type="response", alpha=0.05)
```


```{r}
img <- readPNG("plot.png")
img2 <- readPNG("max2.png")

nd <- as.data.frame(lsmeans$emmeans) 
ggplot(nd, aes(x=reorder(herbicide,prop), y=prop*100, color=herbicide)) + 
 annotation_custom(rasterGrob(img, 
                              width = unit(1,"npc"), 
                               height = unit(1,"npc")), 
                   -Inf, Inf, -Inf, Inf) +
   annotation_custom(rasterGrob(img2, 
                               width = unit(0.7,"npc"), 
                               height = unit(0.15,"npc")), 
                   -Inf, 9, -Inf, 20) +
geom_point(size=5) + ylim(0,100) +
  geom_label(label="Professor: Maxwel C Oliveira, PhD", x = 5.25, y = 44, 
            color="black", fill="white") +
#  annotate("text", x = 5.25, y = 50, label = 'XXXII Congresso Brasileiro da Ciência das Plantas Daninhas', face="bold") +
scale_color_brewer(palette = "Reds") +
#scale_color_manual(values = c("indianred2", "blanchedalmond", "lawngreen",
 #                             "ivory", "aliceblue")) +
theme_bw() + labs(y="Controle (%)", x="Herbicidas", title = "R para análise e visualização de dados na Ciência \n das Plantas Daninhas", subtitle = 'XXXII Congresso Brasileiro da Ciência das Plantas Daninhas', caption='') +
geom_linerange(aes(ymin = lower.CL*100, ymax = upper.CL*100), size=2) + 
theme(axis.title = element_text(size=15, color="black"), panel.grid = element_blank(),
axis.text = element_text(size=13, color="black"), plot.title = element_text(size=16, hjust = 0.5, face="bold", color="red"), plot.caption = element_text(size=12, face='bold', color='black'),
plot.subtitle = element_text(size=13, color="black", hjust = 0.5, face="bold"),
legend.position = "none") +
coord_flip() +
  ggsave("Figure.pdf", height = 6, width=6, dpi=600)
```

```{r}
aa <- c(1:5)
bb <- c('a', 'b', 'c', 'd', 'e')
dat <- data_frame(aa, bb)

ggplot(dat, aes(x=bb, y=aa)) + labs(y="Controle (%)", x="Herbicidas", 
                  title = "Grupo de estudos em Ciência das Plantas Daninhas", 
                  subtitle = 'Universidade do Oeste Paulista', caption='') +
  theme_bw() +
  theme(axis.title = element_blank(), panel.grid = element_blank(), axis.ticks = element_blank(),
axis.text = element_blank(), plot.title = element_text(size=16, hjust = 0.5, face="bold", color="#006729"), plot.caption = element_text(size=12, face='bold', color='#1a171b'), plot.background = element_rect(fill = "#eceded"), 
panel.background = element_rect(fill='#b1c800'),
plot.subtitle = element_text(size=13, color="#1a171b", hjust = 0.5, face="bold"),
legend.position = "none") +
  geom_label(label="Professor: Maxwel C Oliveira, PhD", x = 1.25, y = 3, 
            color="black", fill="white") +
  geom_label(label="Contato: maxweloliveira@unoeste.br", x = 1, y = 3, 
            color="black", fill="white")  +
  annotate("text", x = 5.25, y = 50, label = 'XXXII Congresso Brasileiro da Ciência das Plantas Daninhas', face="bold")
```


```{r}
img <- readPNG("plot.png")
img2 <- readPNG("max2.png")

nd <- as.data.frame(lsmeans$emmeans) 

ggplot(nd, aes(x=reorder(herbicide,prop), y=prop*100, color=herbicide)) + 
geom_point(size=5) + ylim(0,100) +
  geom_label(label="Professor: Maxwel C Oliveira, PhD", x = 1.25, y = 50, 
            color="black", fill="white") +
  geom_label(label="Contato: maxweloliveira@unoeste.br", x = 1, y = 50, 
            color="black", fill="white") +
#  annotate("text", x = 5.25, y = 50, label = 'XXXII Congresso Brasileiro da Ciência das Plantas Daninhas', face="bold") +
scale_color_brewer(palette = "Reds") +
#scale_color_manual(values = c("indianred2", "blanchedalmond", "lawngreen",
 #                             "ivory", "aliceblue")) +
theme_bw() + labs(y="Controle (%)", x="Herbicidas", 
                  title = "Grupo de estudos em Ciência das Plantas Daninhas", 
                  subtitle = 'Universidade do Oeste Paulista', caption='') +
geom_linerange(aes(ymin = lower.CL*100, ymax = upper.CL*100), size=2) + 
theme(axis.title = element_text(size=15, color="#1a171b"), panel.grid = element_blank(),
axis.text = element_text(size=13, color="#1a171b"), plot.title = element_text(size=16, hjust = 0.5, face="bold", color="#006729"), plot.caption = element_text(size=12, face='bold', color='#1a171b'), plot.background = element_rect(fill = "#eceded"), 
plot.subtitle = element_text(size=13, color="#1a171b", hjust = 0.5, face="bold"),
legend.position = "none") +
coord_flip() +
  ggsave("Figure2.pdf", height = 6, width=6, dpi=600)
```
